bt_executer:
  plugins:  ["trajectory_loader_plugin", "move_to_plugin", "move_to_conf_plugin", "wait_plugin"] #,"tool_centering_plugin"]
  bt_package: "bt_executer_examples"
  bt_name: "test_tree_kuka.xml"
  
