bt_executer:

  comau_wait_test:
    wait_ms: 5000 #ms

  comau_trajectory_loader_test:
    group_name: "comau"
    trj_names: ["comau_trj_test"]
    fjt_action_name: "/comau_scaled_fjt_controller/follow_joint_trajectory"
    repetitions: 3
    recompute_time_law: True
    simulation: False
    speed_scaling_topic: "/comau_speed_ovr"
    scaling: 100

  comau_move_to_test:
      group_name: "comau"
      world_name: "world"
      ik_service_name: "/comau_ik_solver/get_ik"
      location_name: "foo_location"
      fjt_action_name: "/comau_scaled_fjt_controller/follow_joint_trajectory"
      simulation: False
      speed_scaling_topic: "/comau_speed_ovr"
      scaling: 100
      pipeline_id: "ompl"
      planner_id: "BiTRRT"
      velocity_scaling_factor: 1
      acceleration_scaling_factor: 1
      joints_weights: [1,1,1,1,1,1]
  